#!/bin/sh

# no longer needed for "Save and Apply" to restart dawn
# luci-app-dawn calls /etc/init.d/privoxy reload
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dawn[-1]
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
ubus call dawn reload_config

exit 0
